# Generated by Django 2.2.5 on 2019-09-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0004_emailverifyrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
