# Generated by Django 2.2.5 on 2019-10-03 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0002_auto_20190928_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstCatage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_catage_title', models.CharField(choices=[(1, '监督学习'), (2, '监督学习'), (3, '模型选择和评估'), (4, '检验'), (5, '数据集转换'), (6, '数据加载工具'), (7, '使用sklearn计算')], help_text='一级目录名称,禁止为空', max_length=50, verbose_name='一级目录名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '一级目录',
                'verbose_name_plural': '一级目录',
                'ordering': ['add_time'],
            },
        ),
        migrations.CreateModel(
            name='SecondCatage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_catage_title', models.CharField(help_text='二级目录名称,禁止为空', max_length=50, verbose_name='二级目录名称')),
                ('second_catage_html', models.TextField(help_text='二级目录主页,禁止为空', verbose_name='二级目录详细介绍')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('second_catage_type', models.ForeignKey(default='未设置二级目录类型', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='second_catage_type', to='data_process.FirstCatage')),
            ],
            options={
                'verbose_name': '二级目录',
                'verbose_name_plural': '二级目录',
                'ordering': ['add_time'],
            },
        ),
    ]
