# Generated by Django 2.2.5 on 2019-10-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0003_firstcatage_secondcatage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstcatage',
            name='first_catage_title',
            field=models.CharField(choices=[('1', '监督学习'), ('2', '监督学习'), ('3', '模型选择和评估'), ('4', '检验'), ('5', '数据集转换'), ('6', '数据加载工具'), ('7', '使用sklearn计算')], help_text='一级目录名称,禁止为空', max_length=50, verbose_name='一级目录名称'),
        ),
    ]
