# Generated by Django 2.2.5 on 2019-10-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0004_auto_20191003_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondcatage',
            name='second_catage_type',
            field=models.ForeignKey(default='未设置二级目录类型', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='second_catage_type', to='data_process.FirstCatage', verbose_name='二级目录类型'),
        ),
    ]
