# Generated by Django 2.2.5 on 2019-10-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0006_auto_20191003_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstcatage',
            name='first_catage_title',
            field=models.CharField(help_text='一级目录名称,禁止为空', max_length=50, verbose_name='一级目录名称'),
        ),
    ]
