# Generated by Django 2.2.5 on 2019-10-03 16:39

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0007_auto_20191003_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondcatage',
            name='second_catage_html',
            field=DjangoUeditor.models.UEditorField(help_text='二级目录主页,禁止为空', verbose_name='二级目录详细介绍'),
        ),
    ]
