# Generated by Django 2.2.5 on 2019-10-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0008_auto_20191003_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstcatage',
            name='first_catage_slug',
            field=models.SlugField(blank=True, help_text='一级目录连接,禁止为空', null=True, verbose_name='一级目录连接'),
        ),
        migrations.AddField(
            model_name='secondcatage',
            name='second_catage_slug',
            field=models.SlugField(blank=True, help_text='一级目录连接,禁止为空', null=True, verbose_name='一级目录连接'),
        ),
    ]
