# Generated by Django 2.2.5 on 2019-10-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0009_auto_20191003_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondcatage',
            name='second_catage_slug',
            field=models.SlugField(blank=True, help_text='二级目录连接,禁止为空', null=True, verbose_name='二级目录连接'),
        ),
    ]
