# Generated by Django 2.2.5 on 2019-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0012_auto_20191004_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondcatage',
            options={'ordering': ['second_catage_order'], 'verbose_name': '二级目录', 'verbose_name_plural': '二级目录'},
        ),
        migrations.AddField(
            model_name='secondcatage',
            name='second_catage_order',
            field=models.IntegerField(blank=True, help_text='二级目录顺序，决定前端目录顺序,允许为空', max_length=11, null=True, verbose_name='二级目录顺序'),
        ),
        migrations.AlterField(
            model_name='firstcatage',
            name='first_catage_slug',
            field=models.SlugField(help_text='一级目录连接,禁止为空,禁止重复', unique=True, verbose_name='一级目录连接'),
        ),
        migrations.AlterField(
            model_name='secondcatage',
            name='second_catage_slug',
            field=models.SlugField(help_text='二级目录连接,禁止为空,禁止重复', unique=True, verbose_name='二级目录连接'),
        ),
    ]
