# Generated by Django 2.2.5 on 2019-10-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0013_auto_20191004_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstcatage',
            name='first_catage_order',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='一级目录顺序，决定前端目录顺序,允许为空', max_digits=5, null=True, verbose_name='一级目录顺序'),
        ),
        migrations.AlterField(
            model_name='secondcatage',
            name='second_catage_order',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='二级目录顺序，决定前端目录顺序,允许为空', max_digits=5, null=True, verbose_name='二级目录顺序'),
        ),
    ]
